# frozen_string_literal: true

# Auto-generated by scripts/update-homebrew-formula.sh — do not edit by hand.
# Regenerated on every release tag by .github/workflows/release.yml.

class GitlabCli < Formula
  desc "Agent-first CLI for legacy GitLab EE 14.0.5"
  homepage "https://github.com/zhiyue/gitlab-cli"
  license "Apache-2.0"
  version "0.2.0"

  # Intel Mac (x86_64-apple-darwin) build is not published; arm64 only.
  # Intel Mac users can install via the curl|sh installer or build from source.
  depends_on arch: :arm64

  on_macos do
    url "https://github.com/zhiyue/gitlab-cli/releases/download/v0.2.0/gitlab-cli-v0.2.0-aarch64-apple-darwin.tar.gz"
    sha256 "879c06c7bb3a8b2c61fe126cd773d5e39988a2ce30af48e5030328bbbd1a0254"
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zhiyue/gitlab-cli/releases/download/v0.2.0/gitlab-cli-v0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "beed9ee9360503fcf3fba3e4e74a07fc66ad5781599db753577dc68b750a4035"
    else
      url "https://github.com/zhiyue/gitlab-cli/releases/download/v0.2.0/gitlab-cli-v0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "30bfcacc441be73b3669f59cfc67ee9026c9c8a1ba38854ba3ec4e299228aa60"
    end
  end

  def install
    bin.install "gitlab"
  end

  test do
    assert_match "gitlab", shell_output("#{bin}/gitlab --version")
  end
end
